### ISSUE TITLE
Backslashes are dangerous - Perhaps change password gen to exclude them

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-generator#2]
Exclude backslashes from generated password.

**Comment by key10** [comment]
I have a couple of questions/thoughts on this, and apologize if this isn't the best place to continue the convo. 

Should the backslashes be completely excluded like this, or would it be better to have them excluded by default with an option to include them if desired? My main thought here is the flexibility it would allow, but at the same time trying to protect from the malicious escaping. 

For efficiency, should we exclude backslashes in the regex pattern that is used to generate the password? The current way works but has the potential to need to generate multiple passwords before passing the `isPasswordSafeEnough` check. 

Just wanted to get your thoughts before I start working on issue #4

**Comment by sallar** [comment]
@key10 If we could construct the Regexp on the fly and include/exclude characters this way, would be the most efficient. Right?

**Comment by perry-mitchell** [comment]
To be perfectly honest, I would like to rewrite the generator’s core as right now we’re dependent on an external library which isn’t ultra flexible. The way it generates characters is very inefficient, and I personally would much prefer a hard coded character set. I would hold off on this task until a more suitable generator is built/found.

Some requirements of the new generator:
 - ability to specify hardcoded character ranges (no need to mess around with regular expressions)
 - more options (uppercase letters, lowercase, numbers, spaces, underscore + dash, symbols)
 - ability to prevent repeated characters
 - ability to prevent repeated items from the same set
 - ability to override the random number generator (for other platforms, and must be async)

If we can satisfy that shopping list, I’d be happy. If not we may need to write our own..

**Comment by key10** [comment]
EDIT: @perry-mitchell beat me to it, but I completely share the same sentiment for the same reasons, the main one being flexibility

@sallar yes, i think so. In order to construct the Regexp dynamically, we would need to use the string syntax of creating `new RegExp(str)`. The biggest thing to be careful of here is (ironically enough) the backslashes for escape characters. An example I found online that relates to the `forbiddenCharsRegex` that was added, is to perform the same _search for a backslash_ using the string syntax, it would be: 
`new RegExp("\\\\", "g")` as opposed to the current `/\\/` 

If you look at how the password-generator code is working, it is doing something very similar (not the 'memorable'/word way, just random chars). It is taking the ascii char set, and testing each one against that regex pattern that is passed in to create a sub-set of valid chars to use. It then assembles the password one letter at a time. 
One option I thought of is to actually pull that functionality into this project to have a little more control on how the passwords are built and to reduce the number of packages pulled in. But that really depends on if the `cli` portion of that project is used/needed, or if its just the generate module. 

Since that module is building one char at a time without any context of existing chars, we are limited in the rules we are able to set. One example that comes to mind is being able to have the rule of `chars shouldn't be repeated more than 2 times consecutively`. 
Rolling our own functionality for that could be something on the roadmap, and isn't a complete need for right now. 

One other thing that I noticed is that in the rule of `only symbols` where our pattern is `/[\W]/`, we are actually excluding the underscore `_` char from available options ([https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp)

**Comment by perry-mitchell** [comment]
I think then we definitely want our own implementation. The crypto+rng part is especially important as we need this to be portable to react native. Crypto there must be done on the native side and transferred over an async channel to the JS.. so this library needs to expose a RNG override.

I would also suggest the following options, which could be rendered as checkboxes in some UI:

- Uppercase letters
- Lowercase letters
- Digits
- Spaces
- Underscores / Dashes
- Symbols (basic keyboard range, no slashes)
- Add from custom set (specified with an input)

I would suggest that all of these be hardcoded - regex is horribly inefficient at this task and should be avoided.

**Comment by perry-mitchell** [comment]
Haha sorry @key10 - good we’re on the same page 😅

**Comment by key10** [comment]
no worries @perry-mitchell, I was just at the very end and didn't want to erase it all haha

I'm onboard with the options we've put together. I think having a basic menu of checkboxes, and then have an advanced menu where the user can specify each individual char they want. 
As for regex, I have no qualms with avoiding it. I feel like I have to relearn it every time I wanna use it. 

What are you thoughts on having hardcoded arrays of the chars for each 'category'/option, and then based on the selected options, we concat/union/intersect to create our `chosenCharSet` set to use when assembling the password? I think going from that angle would allow us to more easily handle the more advanced include/exclude custom sets. 

I'll look around and see how the current module is handling the crypto+rng part, and see if there are other modules that are similar but have more flexibility or how challenging it would be to replicate that portion in this buttercup module

**Comment by perry-mitchell** [comment]
Discussion in #5
